package base;

public enum Genre {
	ARTICLE, BOOK, BOOK_ITEM, PROCEEDINGS, CONFERENCE_PAPER, TALK_AT_EVENT, CONFERENCE_REPORT, POSTER,
	COURSEWARE_LECTURE, THESIS, REPORT, JOURNAL, ISSUE, SERIES, OTHER, EDITORIAL,
	CONTRIBUTION_TO_HANDBOOK, CONTRIBUTION_TO_FESTSCHRIFT, CONTRIBUTION_TO_COMMENTARY,
	CONTRIBUTION_TO_COLLECTED_EDITION, BOOK_REVIEW, CASE_STUDY, CASE_NOTE, ENCYCLOPEDIA,
	COMMENTARY, HANDBOOK, COLLECTED_EDITION, FESTSCHRIFT, PATENT, NEWSPAPER_ARTICLE, PAPER,
	MANUSCRIPT, MANUAL, OPINION, MONOGRAPH, NEWSPAPER, MULTI_VOLUME, MEETING_ABSTRACT, FILM
}
